cache:
  directories:
  - $HOME/.m2
matrix:
  include:
  - os: linux
    sudo: required
    dist: xenial
    language: java
    jdk: openjdk11
  - os: osx
    language: java
    osx_image: xcode10.1
notifications:
  email:
  - ben.alex@acegi.com.au
  - stoffe@gmail.com
before_install:
  - gpg --version
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install binutils-mingw-w64-x86-64; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install gcc-mingw-w64-base; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install mingw-w64-common; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install mingw-w64-x86-64-dev; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install gcc-mingw-w64-x86-64; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install unzip; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then wget https://dl.google.com/android/repository/android-ndk-r19b-linux-x86_64.zip -O ndk.zip && unzip ndk.zip && export NDK=`pwd`/ndk; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then export JAVA_HOME=$(/usr/libexec/java_home); fi
install:
  - mvn -B -Pdeploy -DexcludeGroupIds=com.github.github -V dependency:go-offline
script:
  - mvn -B -Pdeploy -Dgpg.skip=true verify
after_success:
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_TAG" == "" ]; then echo $GPG_KEY | base64 --decode | gpg --batch --fast-import -; fi
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_TAG" == "" ]; then mvn -B -P deploy --settings .travis-settings.xml deploy; fi
